name: Run the action

on:
    push:
        branches:
            - main

jobs:
    call-resuable-workflows:
        uses: aggarwalmegha/test-github-actions/.github/workflows/pull-request.yml@test-branch
        with:
            ci-env: python